## 问题： 求y = w^2 - 10*w +25的最小值

## tensorflow求导的方法

In [140]:
import numpy as np
import tensorflow as tf

In [141]:
w = tf.Variable(0, dtype=tf.float32)

In [142]:
cost = tf.add(tf.add(w**2, tf.multiply(-10., w)), 100.0)
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

init = tf.global_variables_initializer()
session = tf.Session()
session.run(init)
print(session.run(w))
print(session.run(cost))

0.0
100.0


In [143]:
for i in range(1000):
    _, c = session.run([train, cost])
#     print(_)
    print(c)
print(session.run(w))  # 1000次迭代后w的取值
print(session.run(cost))  # 算出此时cost的值

100.0
99.01
98.0592
97.1461
96.2691
95.4268
94.6179
93.841
93.0949
92.3784
91.6902
91.0293
90.3945
89.7849
89.1994
88.6371
88.0971
87.5784
87.0803
86.6019
86.1425
85.7013
85.2775
84.8705
84.4796
84.1042
83.7437
83.3975
83.0649
82.7456
82.4388
82.1443
81.8613
81.5896
81.3287
81.0781
80.8374
80.6062
80.3842
80.171
79.9662
79.7696
79.5807
79.3993
79.2251
79.0578
78.8971
78.7428
78.5945
78.4522
78.3155
78.1842
78.0581
77.937
77.8207
77.709
77.6017
77.4987
77.3997
77.3047
77.2134
77.1258
77.0416
76.9608
76.8831
76.8085
76.7369
76.6681
76.6021
76.5386
76.4777
76.4192
76.363
76.309
76.2572
76.2074
76.1596
76.1137
76.0696
76.0272
75.9865
75.9475
75.9099
75.8739
75.8393
75.8061
75.7742
75.7435
75.7141
75.6858
75.6586
75.6325
75.6075
75.5834
75.5603
75.5381
75.5168
75.4964
75.4767
75.4578
75.4397
75.4223
75.4056
75.3895
75.3741
75.3593
75.345
75.3314
75.3183
75.3056
75.2935
75.2819
75.2708
75.26
75.2497
75.2398
75.2303
75.2212
75.2125
75.2041
75.196
75.1882
75.1808
75.1736
75.1667
75.1601
75.153

## 注入data

In [86]:
w = tf.Variable(0, dtype=tf.float32)
coeficients = np.array([[1.], [-10.], [26.]])
x = tf.placeholder(tf.float32, [3, 1])

In [87]:
cost = x[0][0] * w **2 + x[1][0] * w + x[2][0]
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
init = tf.global_variables_initializer()
session = tf.Session()
session.run(init)
print(session.run(w))

session.run(train, feed_dict={x: coeficients})
print(session.run(w))

0.0
0.1


In [89]:
for i in range(1000):
    session.run(train, feed_dict={x: coeficients})
print(session.run(w))
print(session.run(cost, feed_dict={x:coeficients}))

4.99999
1.0


## mxnet求导的方法

In [29]:
import mxnet.ndarray as nd
import mxnet.autograd as ag

In [30]:
x = nd.array([0])
x.attach_grad()  # 当进行求导的时候，我们需要一个地方来存x的导数，这个可以通过NDArray的方法attach_grad()来要求系统申请对应的空间。

In [31]:
def SGD(x, lr):
    x[:] = x - lr * x.grad
    
def f(x):
    return x ** 2 - 10 * x + 25

In [32]:
for i in range(1000):
    with ag.record(): # 默认情况下, MXNet不会自动记录和构建用于求导的计算图，我们需要使用autograd里的record()函数来显式的要求MXNet记录我们需要求导的程序。
        y = f(x)
    y.backward()
    SGD(x, 0.01)

In [40]:
print(x)  # 1000次迭代后x的取值
print(x.grad)
print(f(x))


[ 4.99998856]
<NDArray 1 @cpu(0)>

[ -2.28881836e-05]
<NDArray 1 @cpu(0)>

[ 0.]
<NDArray 1 @cpu(0)>


In [90]:
r = np.random.rand() # [0, 1]均匀分布
beta = 1-10**(- r - 1)
print(beta)

0.9848785337744963


## numpy 练习

In [107]:
a = np.arange(20).reshape((5,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [93]:
print(a[[0, 1, 3], :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]]


In [99]:
a[[0, 1, 3]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [103]:
row_idx = np.array([0, 1, 3])
col_idx = np.array([0, 2])

In [109]:
a[np.ix_([0,1,3], [0,2])]

array([[ 0,  2],
       [ 4,  6],
       [12, 14]])

In [111]:
import numpy as np
def convert_to_one_hot(Y, C):
    """
    Y是一个numpy.array vector, C是分类的种数
    """
    Y = np.eye(C)[Y.reshape(-1)].T
    return Y

In [123]:
y = np.array([[1, 2, 3, 0, 2, 1]])
print(y.shape)
print(y.reshape(-1).shape)
C = 4
print(convert_to_one_hot(y, C))

(1, 6)
(6,)
[[ 0.  0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.]]


In [126]:
y = np.array([[[1, 2, 3, 0, 2, 1], [12, 21, 31, 10, 21, 18]], [[1, 2, 3, 0, 2, 1], [10, 26, 36, 60, 27, 91]]])
y.reshape(-1)

array([ 1,  2,  3,  0,  2,  1, 12, 21, 31, 10, 21, 18,  1,  2,  3,  0,  2,
        1, 10, 26, 36, 60, 27, 91])

In [127]:
np.reshape?